function [Tauu,Tauv,dTauudu,dTauvdv,dTauudv,dTauvdu,dTauudh,dTauvdh] = rCWN0(C,C0,N,dNdh,He,delta,m,mu,u,v,u0)


%SLIDINGSYMBOLIC
%    [TAUU,TAUV,DTAUUDU,DTAUVDV,DTAUUDV,DTAUVDU,DTAUUDH,DTAUVDH] = SLIDINGSYMBOLIC(C,C0,H,HF,M,MU,U,U0,V)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Feb-2020 17:16:18

t2 = N;
t3 = mu.^2;
t4 = u.^2;
t5 = u0.^2;
t6 = v.^2;
t7 = C+C0;
% t10 = -hf;
t11 = m-1.0;
t13 = 1.0./m;
t8 = t2.^2;
t9=dNdh ; % t9 = diff(t2,h);
t12 = t11-1.0;
% t14 = h+t10;
t17 = t7.^t13;
t18 = t13./2.0;
t20 = t4+t5+t6;
t30 = t11.*t13.*(-1.0./2.0);
t15=delta ; % t15 = dirac(t14);
t16=He ; % t16 = heaviside(t14);
% t19=0 ; % t19 = (t14 == 0.0);  ?! for some reason the simplificatoin gives a kronecka delta function
t22 = mu.*t2.*t17;
%t23 = t11.*t18;
%t24 = t12.*t18;
t27 = t18-1.0./2.0;
t28 = t18-3.0./2.0;
t31 = t12.*t13.*(-1.0./2.0);
t34 = t20.^t18;
t36 = t20.^t30;
% t21=0 ; % t21 = t19./4.0;
t25 = m.*t22;
t29 = t22.*2.0;
t32 = -t22;
t37 = t20.^t31;
t38 = t20.^t27;
t39 = t20.^t28;
t40 = t16.*t34;
t26=0 ; % t26 = -t21;
t33 = t5.*t25;
t41 = m.*t40;
t43 = t29+t34;
t45 = t22+t40;
t35 = t16+t26;
t42 = t5.*t41;
t44 = 1.0./t43.^2;
t46 = 1.0./t45;
Tauu = mu.*t2.*t16.*t38.*t46.*u;
if nargout > 1
    Tauv = mu.*t2.*t16.*t38.*t46.*v;
end
if nargout > 2
    t48 = t25+t32+t41;
    t47 = t46.^2;
    dTauudu = mu.*t2.*t13.*t16.*t39.*t47.*(t33+t42+t4.*t22+t6.*t25+t6.*t41);
end
if nargout > 3
    dTauvdv = mu.*t2.*t13.*t16.*t39.*t47.*(t33+t42+t6.*t22+t4.*t25+t4.*t41);
end
if nargout > 4
    t49 = mu.*t2.*t13.*t16.*t39.*t47.*t48.*u.*v;
    t50 = -t49;
    dTauudv = t50;
end
if nargout > 5
    dTauvdu = t50;
end
if nargout > 6
    dTauudh = mu.*t9.*t35.*t37.*t47.*u+t3.*t8.*t15.*t17.*t36.*t44.*u.*4.0;
end
if nargout > 7
    dTauvdh = mu.*t9.*t35.*t37.*t47.*v+t3.*t8.*t15.*t17.*t36.*t44.*v.*4.0;
end
