



%function [Tauu,Tauv,dTauudu,dTauvdv,dTauudv,dTauvdu,dTauudh,dTauvdh] = rCWV0(C,C0,V0,h,hf,m,u,v,u0)
function [Tauu,Tauv,dTauudu,dTauvdv,dTauudv,dTauvdu,dTauudh,dTauvdh] = rCWV0(C,C0,V0,He,delta,m,u,v,u0)
%rCWV0
%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    21-Nov-2023 16:30:23

t2 = V0.*m;
t3 = u.^2;
t4 = u0.^2;
t5 = v.^2;
t6 = C+C0;
t7 = -V0;
% t8 = -hf;
t9 = 1.0./m;
% t10 = h+t8;   % h-hf 
t11 = t2.*t4;
t12 = -t9;
t15 = t9./2.0;
t17 = t3+t4+t5;
t13 = delta; % t13 = dirac(t10);
t14 = He;  % t14 = heaviside(t10);
t16 = t12-1.0;
t18 = t6.^t12;
t19 = t15-1.0./2.0;
t20 = t15-3.0./2.0;
t21 = sqrt(t17);
t22 = m.*t21;
t23 = V0+t21;
t27 = t17.^t19;
t28 = t17.^t20;
t24 = t4.*t22;
t25 = t2+t7+t22;
t26 = t23.^t12;
Tauu = t14.*t18.*t26.*t27.*u;
if nargout > 1
    Tauv = t14.*t18.*t26.*t27.*v;
end
if nargout > 2
    t29 = t23.^t16;
    dTauudu = t9.*t14.*t18.*t28.*t29.*(t11+t24+V0.*t3+t2.*t5+t5.*t22);
end
if nargout > 3
    dTauvdv = t9.*t14.*t18.*t28.*t29.*(t11+t24+V0.*t5+t2.*t3+t3.*t22);
end
if nargout > 4
    t31 = t12.*t14.*t18.*t25.*t28.*t29.*u.*v;
    dTauudv = t31;
end
if nargout > 5
    dTauvdu = t31;
end
if nargout > 6
    dTauudh = t13.*t18.*t26.*t27.*u;
end
if nargout > 7
    dTauvdh = t13.*t18.*t26.*t27.*v;
end
end
