function [Tauu,Tauv,dTauudu,dTauvdv,dTauudv,dTauvdu,dTauudh,dTauvdh] = rpCWN0(C,C0,N,dNdh,He,delta,m,mu,u,v,u0)
    
    

%%
    % Tau=TauC*TauW/( (TauW^m+TauC^m)^(1/m));   % Inverse weighting
    %    This function was generated by the Symbolic Math Toolbox version 8.4.
    %    02-Feb-2020 17:28:58
    

  
    t2=N ; % t2 = N(h);
    t3 = mu.^m;
    t4 = m.*3.0;
    t5 = m+1.0;
    t6 = 2.0.^m;
    t7 = u.^2;
    t8 = u0.^2;
    t9 = v.^2;
    t10 = C+C0;
    % t13 = -hf;
    t14 = m-1.0;
    t15 = 1.0./m;
    t11=dNdh ; % t11 = diff(t2,h);
    t12 = t2.^m;
    t16 = 2.0.^t5;
    t17 = mu.^t5;
    t18 = t4-1.0;
    t20 = t15.*2.0;
    % t21 = h+t13;
    t22 = t2.^t5;
    t23 = -t15;
    t28 = t15./2.0;
    % t29 = t5.*t15;
    t32 = t7+t8+t9;
    t42 = t14.*t15.*(-1.0./2.0);
    t19 = t18-1.0;
    t24 = -t20;
    t25=delta ; % t25 = dirac(t21);
    t26=He ; % t26 = heaviside(t21);
    t27 = t3.*t12;
    t31 = t23-1.0;
    t33 = t5.*t23;
    t35 = t10.^t23;
    % t39 = t14.*t28;
    t40 = t28-1.0./2.0;
    t41 = t28-3.0./2.0;
    % t43 = t18.*t28;
    t45 = t15.*t18.*(-1.0./2.0);
    t47 = t32.^t28;
    t48 = t32.^t42;
    t30 = t26.^m;
    t34 = t26.^t5;
    t36 = t10.^t24;
    t37 = t6.*t27;
    t38 = m.*t8.*t27;
    % t44 = t19.*t28;
    t46 = t15.*t19.*(-1.0./2.0);
    t49 = t32.^t40;
    t50 = t32.^t41;
    t51 = t32.^t45;
    t53 = t35.*t47;
    t52 = t32.^t46;
    t54 = t53.^m;
    t55 = t53.^t14;
    t56 = t30.*t54;
    t57 = t37+t54;
    t58 = m.*t8.*t56;
    t59 = t27+t56;
    t60 = t57.^t33;
    t61 = t59.^t23;
    Tauu = mu.*t2.*t26.*t35.*t49.*t61.*u;
    if nargout > 1
        Tauv = mu.*t2.*t26.*t35.*t49.*t61.*v;
    end
    if nargout > 2
        t62 = t59.^t31;  % t59 sometimes becomes just slighly negative
        dTauudu = mu.*t2.*t15.*t26.*t35.*t50.*t62.*(t38+t58+t7.*t27+m.*t9.*t27+m.*t9.*t56);
    end
    if nargout > 3
        dTauvdv = mu.*t2.*t15.*t26.*t35.*t50.*t62.*(t38+t58+t9.*t27+m.*t7.*t27+m.*t7.*t56);
    end
    if nargout > 4
        t63 = t59.^t33;
        % t64 = mu.*t2.*t14.*t15.*t26.*t35.*t51.*t61.*u.*v;
        t65 = mu.*t2.*t14.*t23.*t26.*t35.*t51.*t61.*u.*v;
        % t66 = mu.*t2.*t15.*t34.*t36.*t52.*t55.*t63.*u.*v;
        t67 = mu.*t2.*t23.*t34.*t36.*t52.*t55.*t63.*u.*v;
        t68 = t65+t67;
        dTauudv = t68;
    end
    if nargout > 5
        dTauvdu = t68;
    end
    if nargout > 6
        dTauudh = t16.*t17.*t22.*t25.*t35.*t48.*t60.*u+mu.*t11.*t34.*t35.*t48.*t54.*t63.*u;
    end
    if nargout > 7
        dTauvdh = t16.*t17.*t22.*t25.*t35.*t48.*t60.*v+mu.*t11.*t34.*t35.*t48.*t54.*t63.*v;
    end
    
    
    
end