%%

load TestSave




detJw=detJ*MUA.weights(Iint);
nod=MUA.nod ; 



tic
[Tx,Fx,Ty,Fy,Th,Fh,Kxu,Kxv,Kyu,Kyv,Kxh,Kyh,Khu,Khv,Khh]=...
    uvhNodalLoopSSTREAM(detJw,nod,theta,tau0,Ronly,...
    CtrlVar,Tx,Fx,Ty,Fy,Th,Fh,Kxu,Kxv,Kyu,Kyv,Kxh,Kyh,Khu,Khv,Khh, ...
    Deriv,fun,...
    exx,eyy,exy,exx0,eyy0,...
    dhdx,dhdy,dh0dx,dh0dy,drhodx,drhody,dbdx,dbdy,dBdx,dBdy,Hposint,Dddhint,...
    ca,sa,g,dt,...
    etaint,Eint,...
    h0barr,h1barr,...
    taux,tauy,dtauxdu,dtauxdv,dtauydu,dtauydv,dtauxdh,dtauydh,...
    Heint,deltaint,rhoint,rhow,uint,vint,u0int,v0int,dint,...
    hint,h0int,a1int,a0int,dadhint,lambda_h) ; 
toc